"use server";

import { revalidatePath } from "next/cache";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { db } from "@/db";
import { emails, emailThreads, type ExtractedLead } from "@/db/schema";
import { requireOffice as requireUser } from "@/lib/auth";
import { createLeadFromEmail, linkThread, markEmailNotLead, processEmail } from "@/lib/email/pipeline";
import { sendReply } from "@/lib/email/smtp";
import { LEAD_URGENCIES } from "@/lib/constants";
import { ok, fail, type ActionResult } from "@/lib/action-result";

function revalidateInbox(threadId?: string) {
  revalidatePath("/inbox");
  if (threadId) revalidatePath(`/inbox/${threadId}`);
  revalidatePath("/leads");
}

const optionalText = z
  .string()
  .trim()
  .transform((v) => (v === "" ? null : v))
  .nullable()
  .optional();

const reviewInput = z.object({
  contact_name: optionalText,
  company: optionalText,
  email: optionalText,
  phone: optionalText,
  service: optionalText,
  site_address: optionalText,
  summary: z.string().trim().optional(),
  urgency: z.enum(LEAD_URGENCIES).optional(),
  next_action: z.string().trim().optional(),
  assignedToId: z
    .string()
    .trim()
    .transform((v) => (v === "" ? null : v))
    .pipe(z.string().uuid().nullable())
    .nullable()
    .optional(),
});

/** Reviewer accepts (optionally edits) the AI suggestion and creates the lead. */
export async function acceptEmailAsLead(emailId: string, input: unknown): Promise<ActionResult<{ leadId: string }>> {
  const user = await requireUser();
  const parsed = reviewInput.safeParse(input ?? {});
  if (!parsed.success) return fail(parsed.error.issues[0]?.message ?? "Invalid input");
  const { assignedToId, ...rest } = parsed.data;
  const overrides: Partial<ExtractedLead> = {};
  for (const [k, v] of Object.entries(rest)) if (v !== undefined) (overrides as Record<string, unknown>)[k] = v;
  try {
    const leadId = await createLeadFromEmail(emailId, { actorId: user.id, overrides, assignedToId: assignedToId ?? null });
    const e = await db.query.emails.findFirst({ where: eq(emails.id, emailId), columns: { threadId: true } });
    revalidateInbox(e?.threadId);
    return ok({ leadId });
  } catch (err) {
    return fail(err instanceof Error ? err.message : String(err));
  }
}

export async function rejectEmailAsLead(emailId: string): Promise<ActionResult<undefined>> {
  const user = await requireUser();
  await markEmailNotLead(emailId, user.id);
  const e = await db.query.emails.findFirst({ where: eq(emails.id, emailId), columns: { threadId: true } });
  revalidateInbox(e?.threadId);
  return ok(undefined);
}

export async function reclassifyEmail(emailId: string): Promise<ActionResult<{ classification: string; detail: string }>> {
  await requireUser();
  const out = await processEmail(emailId, { force: true });
  const e = await db.query.emails.findFirst({ where: eq(emails.id, emailId), columns: { threadId: true } });
  revalidateInbox(e?.threadId);
  return ok({ classification: out.classification, detail: out.detail });
}

export async function linkThreadTo(
  threadId: string,
  target: { leadId?: string | null; contactId?: string | null; jobId?: string | null },
): Promise<ActionResult<undefined>> {
  const user = await requireUser();
  try {
    await linkThread(threadId, target, user.id);
    revalidateInbox(threadId);
    return ok(undefined);
  } catch (err) {
    return fail(err instanceof Error ? err.message : String(err));
  }
}

export async function unlinkThread(threadId: string): Promise<ActionResult<undefined>> {
  await requireUser();
  await db.transaction(async (tx) => {
    await tx.update(emailThreads).set({ leadId: null, contactId: null, jobId: null, updatedAt: new Date() }).where(eq(emailThreads.id, threadId));
    await tx.update(emails).set({ leadId: null, contactId: null }).where(eq(emails.threadId, threadId));
  });
  revalidateInbox(threadId);
  return ok(undefined);
}

const replyInput = z.object({
  threadId: z.string().uuid(),
  inReplyToEmailId: z.string().uuid().nullable().optional(),
  to: z.string().trim().min(1, "Add at least one recipient"),
  cc: z.string().trim().optional(),
  subject: z.string().trim().min(1, "Subject is required"),
  text: z.string().trim().min(1, "Write a message"),
});

function splitAddresses(s: string | undefined): string[] {
  return (s ?? "")
    .split(/[,;\s]+/)
    .map((a) => a.trim())
    .filter((a) => a.includes("@"));
}

/** Send a human-written reply via the mailbox's SMTP. Nothing here is generated by AI. */
export async function sendThreadReply(input: unknown): Promise<ActionResult<{ emailId: string }>> {
  const user = await requireUser();
  const parsed = replyInput.safeParse(input);
  if (!parsed.success) return fail(parsed.error.issues[0]?.message ?? "Invalid input");
  const d = parsed.data;
  const thread = await db.query.emailThreads.findFirst({ where: eq(emailThreads.id, d.threadId) });
  if (!thread) return fail("Thread not found");
  const to = splitAddresses(d.to);
  if (to.length === 0) return fail("Add at least one valid recipient address");
  try {
    const res = await sendReply({
      mailboxId: thread.mailboxId,
      threadId: thread.id,
      inReplyToEmailId: d.inReplyToEmailId ?? null,
      to,
      cc: splitAddresses(d.cc),
      subject: d.subject,
      text: d.text,
      sentById: user.id,
      fromName: user.name,
    });
    revalidateInbox(thread.id);
    return ok({ emailId: res.emailId });
  } catch (err) {
    return fail(`Send failed: ${err instanceof Error ? err.message : String(err)}`);
  }
}

export async function searchLinkTargets(q: string) {
  await requireUser();
  const term = `%${q.trim()}%`;
  const [leadRows, contactRows, jobRows] = await Promise.all([
    db.query.leads.findMany({
      where: q.trim() ? (l, { or, sql }) => or(sql`${l.name} ilike ${term}`, sql`${l.company} ilike ${term}`, sql`${l.email} ilike ${term}`) : undefined,
      columns: { id: true, name: true, company: true, status: true },
      orderBy: (l, { desc }) => [desc(l.updatedAt)],
      limit: 8,
    }),
    db.query.contacts.findMany({
      where: q.trim() ? (c, { or, sql }) => or(sql`${c.name} ilike ${term}`, sql`${c.company} ilike ${term}`, sql`${c.email} ilike ${term}`) : undefined,
      columns: { id: true, name: true, company: true },
      orderBy: (c, { desc }) => [desc(c.updatedAt)],
      limit: 8,
    }),
    db.query.jobs.findMany({
      where: q.trim() ? (j, { or, sql }) => or(sql`${j.title} ilike ${term}`, sql`cast(${j.number} as text) ilike ${term}`) : undefined,
      columns: { id: true, number: true, title: true, status: true },
      orderBy: (j, { desc }) => [desc(j.updatedAt)],
      limit: 8,
    }),
  ]);
  return { leads: leadRows, contacts: contactRows, jobs: jobRows };
}
