import { chromium } from "@playwright/test";
const base = "http://127.0.0.1:3100";
const out = process.env.OUT;
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, timezoneId: "Pacific/Auckland" });
const page = await ctx.newPage();
await page.goto(base + "/login");
await page.getByLabel("Email").fill("admin@getsecure.co.nz");
await page.getByLabel("Password").fill("change-me");
await page.getByRole("button", { name: "Sign in" }).click();
await page.waitForURL(/\/dashboard$/);
await page.screenshot({ path: out + "/dashboard.png", fullPage: true });
const d = new Date(); d.setDate(d.getDate() + 1);
const ymd = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
await page.goto(base + `/calendar?view=day&date=${ymd}`);
await page.waitForSelector("[data-testid^=col-]");
await page.screenshot({ path: out + "/calendar-day.png" });
const m = await ctx.newPage(); await m.setViewportSize({ width: 390, height: 844 });
await m.goto(base + `/my-day?date=${ymd}&tech=all`);
await m.waitForSelector("text=jobs");
await m.screenshot({ path: out + "/my-day.png", fullPage: true });
await browser.close();
